name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install system dependencies
      run: sudo apt install -y blueprint-compiler clang libadwaita-1-dev libgtk-4-dev libssl-dev

    - uses: actions/checkout@v3
    - name: Build backend
      run: cargo build --verbose --bin=backend
